export const countryNameToCode: Record<string, string> = {
  Canada: 'ca',
  China: 'cn',
  Qatar: 'qa',
  Switzerland: 'ch',
  India: 'in',
  Australia: 'au',
  Japan: 'jp',
  Norway: 'no',
  'United Kingdom': 'gb',
  UK: 'gb',
  Britain: 'gb',
  England: 'gb',
  Scotland: 'gb',
  Wales: 'gb',
  'United States': 'us',
  USA: 'us',
  'United States of America': 'us',
  America: 'us',
  France: 'fr',
  Germany: 'de',
  Italy: 'it',
  Spain: 'es',
  Portugal: 'pt',
  Netherlands: 'nl',
  Belgium: 'be',
  Luxembourg: 'lu',
  Austria: 'at',
  Ireland: 'ie',
  Denmark: 'dk',
  Sweden: 'se',
  Finland: 'fi',
  Iceland: 'is',
  Poland: 'pl',
  Ukraine: 'ua',
  Armenia: 'am',
  Հայաստան: 'am',
  Turkey: 'tr',
  Türkiye: 'tr',
  Greece: 'gr',
  Cyprus: 'cy',
  Israel: 'il',
  Palestine: 'ps',
  Jordan: 'jo',
  Egypt: 'eg',
  'Saudi Arabia': 'sa',
  'United Arab Emirates': 'ae',
  UAE: 'ae',
  Kuwait: 'kw',
  Bahrain: 'bh',
  Oman: 'om',
  Lebanon: 'lb',
  Iraq: 'iq',
  Iran: 'ir',
  Pakistan: 'pk',
  Bangladesh: 'bd',
  Nepal: 'np',
  Bhutan: 'bt',
  'Sri Lanka': 'lk',
  Thailand: 'th',
  Vietnam: 'vn',
  Singapore: 'sg',
  Malaysia: 'my',
  Indonesia: 'id',
  Philippines: 'ph',
  'South Korea': 'kr',
  Korea: 'kr',
  'North Korea': 'kp',
  Taiwan: 'tw',
  'Hong Kong': 'hk',
  Mongolia: 'mn',
  Kazakhstan: 'kz',
  Uzbekistan: 'uz',
  Kyrgyzstan: 'kg',
  Tajikistan: 'tj',
  Turkmenistan: 'tm',
  Georgia: 'ge',
  Azerbaijan: 'az',
  Kosovo: 'xk',
  Albania: 'al',
  Serbia: 'rs',
  Croatia: 'hr',
  Slovenia: 'si',
  'Bosnia and Herzegovina': 'ba',
  Montenegro: 'me',
  Macedonia: 'mk',
  'North Macedonia': 'mk',
  Romania: 'ro',
  Bulgaria: 'bg',
  Hungary: 'hu',
  Czechia: 'cz',
  'Czech Republic': 'cz',
  Slovakia: 'sk',
  Estonia: 'ee',
  Latvia: 'lv',
  Lithuania: 'lt',
  Moldova: 'md',
  Belarus: 'by',
  Russia: 'ru',
  Morocco: 'ma',
  Algeria: 'dz',
  Tunisia: 'tn',
  Libya: 'ly',
  Sudan: 'sd',
  Ethiopia: 'et',
  Kenya: 'ke',
  Tanzania: 'tz',
  Uganda: 'ug',
  Rwanda: 'rw',
  Nigeria: 'ng',
  Ghana: 'gh',
  Senegal: 'sn',
  'South Africa': 'za',
  Mexico: 'mx',
  Brazil: 'br',
  Argentina: 'ar',
  Chile: 'cl',
  Peru: 'pe',
  Colombia: 'co',
  Ecuador: 'ec',
  Uruguay: 'uy',
  Paraguay: 'py',
  Bolivia: 'bo',
  Venezuela: 've',
  'New Zealand': 'nz',
  Fiji: 'fj',
  'Vatican City': 'va',
  'Holy See': 'va',
};

export const cityNameToCode: Record<string, string> = {
  Ottawa: 'ca',
  Toronto: 'ca',
  Vancouver: 'ca',
  Calgary: 'ca',
  Montreal: 'ca',
  Quebec: 'ca',
  Edmonton: 'ca',
  Winnipeg: 'ca',
  Halifax: 'ca',
  Yerevan: 'am',
  Geneva: 'ch',
  Zurich: 'ch',
  Bern: 'ch',
  Doha: 'qa',
  Beijing: 'cn',
  Shanghai: 'cn',
  Tokyo: 'jp',
  Oslo: 'no',
  London: 'gb',
  Delhi: 'in',
  Mumbai: 'in',
  Sydney: 'au',
  Melbourne: 'au',
  Rome: 'it',
  'Vatican City': 'va',
};
